### ISSUE TITLE
Panic when switching to notifications or favorited timeline

### ISSUE THREAD

**Issue by tournemire** [RasmusLindroth/tut#113]
Tut 0.0.42 panics when I execute `:timeline notifications` or `:timeline favorited`. Switching to others timelines works as expected. This happens regardless of the currently displayed timeline.

Tut is run from a nix shell on nixos-unstable. 

Stack trace:
```panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x170 pc=0x84c99a]

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1(0xc000322000)
	github.com/rivo/tview@v0.0.0-20211202162923-2a6de950f73b/application.go:243 +0x87
panic(0x8e3960, 0xc84650)
	runtime/panic.go:965 +0x1b9
main.showTootOptions(0xc0003010e0, 0x0, 0x0, 0x95efd3, 0x2, 0xc00003faa0, 0x5b)
	github.com/RasmusLindroth/tut/feed.go:106 +0x3a
main.(*NotificationsFeed).DrawToot(0xc000306040)
	github.com/RasmusLindroth/tut/feed.go:1351 +0x1072
main.(*StatusView).AddFeed(0xc00032a150, 0xa095f0, 0xc000306040)
	github.com/RasmusLindroth/tut/statusview.go:113 +0xee
main.(*CmdBar).DoneFunc(0xc0003045b0, 0xd)
	github.com/RasmusLindroth/tut/cmdbar.go:149 +0x557
main.main.func1(0xc0002941c0, 0xc000513800)
	github.com/RasmusLindroth/tut/main.go:181 +0xec
github.com/rivo/tview.(*Application).Run(0xc000322000, 0x0, 0x0)
	github.com/rivo/tview@v0.0.0-20211202162923-2a6de950f73b/application.go:318 +0x84e
main.main()
	github.com/RasmusLindroth/tut/main.go:331 +0x1036```

**Comment by tournemire** [comment]
Closing because I can no longer reproduce this error.
