### ISSUE TITLE
tut crashes when editing reply

### ISSUE THREAD

**Issue by benjaminbhollon** [RasmusLindroth/tut#189]
I was testing out the brand new shiny editing feature, which worked like a charm when editing my original post, but crashed tut when editing this reply:

https://fosstodon.org/@benjaminhollon/109401485784650218

Here was the output to the terminal:

```
benjamin@archimedes ~/Downloads]$ tut
panic: interface conversion: interface {} is string, not mastodon.ID [recovered]
	panic: interface conversion: interface {} is string, not mastodon.ID

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1()
	/home/rasmus/go/pkg/mod/github.com/rivo/tview@v0.0.0-20221117065207-09f052e6ca98/application.go:244 +0x4d
panic({0x8dcd60, 0xc00015c2d0})
	/usr/lib/go/src/runtime/panic.go:884 +0x212
github.com/RasmusLindroth/tut/ui.(*ComposeView).Post(0xc0001674a0)
	/tmp/tutbuild2038498025/ui/composeview.go:424 +0x985
github.com/RasmusLindroth/tut/ui.(*TutView).InputComposeView(0xc0003d3740?, 0x0?)
	/tmp/tutbuild2038498025/ui/input.go:809 +0x557
github.com/RasmusLindroth/tut/ui.(*TutView).Input(0xc0003e4000, 0xc000382120?)
	/tmp/tutbuild2038498025/ui/input.go:42 +0xf5
github.com/rivo/tview.(*Application).Run(0xc0003300e0)
	/home/rasmus/go/pkg/mod/github.com/rivo/tview@v0.0.0-20221117065207-09f052e6ca98/application.go:319 +0x66d
main.main()
	/tmp/tutbuild2038498025/main.go:45 +0x44f
benjamin@archimedes ~/Downloads]$ tut
panic: interface conversion: interface {} is string, not mastodon.ID [recovered]
	panic: interface conversion: interface {} is string, not mastodon.ID

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1()
	/home/rasmus/go/pkg/mod/github.com/rivo/tview@v0.0.0-20221117065207-09f052e6ca98/application.go:244 +0x4d
panic({0x8dcd60, 0xc00049f350})
	/usr/lib/go/src/runtime/panic.go:884 +0x212
github.com/RasmusLindroth/tut/ui.(*ComposeView).Post(0xc0004af8c0)
	/tmp/tutbuild2038498025/ui/composeview.go:424 +0x985
github.com/RasmusLindroth/tut/ui.(*TutView).InputComposeView(0xc0000d5620?, 0x0?)
	/tmp/tutbuild2038498025/ui/input.go:809 +0x557
github.com/RasmusLindroth/tut/ui.(*TutView).Input(0xc0000000a0, 0xc000324080?)
	/tmp/tutbuild2038498025/ui/input.go:42 +0xf5
github.com/rivo/tview.(*Application).Run(0xc0003ce0e0)
	/home/rasmus/go/pkg/mod/github.com/rivo/tview@v0.0.0-20221117065207-09f052e6ca98/application.go:319 +0x66d
main.main()
	/tmp/tutbuild2038498025/main.go:45 +0x44f
```

**Comment by HelmicNewciv** [comment]
Same, same message.  I think it is specifically only with replies, I could edit my pins just fine but editing a reply got that message.

**Comment by benjaminbhollon** [comment]
Got a very similar message when editing another reply, so yes, I think it's reply-related.

**Comment by RasmusLindroth** [comment]
Oops. I will try to fix this today. Thanks for finding and reporting the bug!

**Comment by RasmusLindroth** [comment]
It now fixed :)

**Comment by benjaminbhollon** [comment]
Very impressed with the speed of handling this. Thanks!
