### ISSUE TITLE
crashes when scrolling through notifications

### ISSUE THREAD

**Issue by soilDNRA** [RasmusLindroth/tut#266]
Using Arch Linux on x86-64. Pressed N to view notifications, then pressed J a couple of times to look through them, then crashed with this output:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x170 pc=0x89849e]

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1()
	/home/erici/go/pkg/mod/github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/application.go:244 +0x4d
panic({0x920720, 0xdd3a90})
	/usr/lib/go/src/runtime/panic.go:884 +0x212
github.com/RasmusLindroth/tut/ui.drawStatus(0xc0000c6420, {0xa877c0, 0xc000034480}, 0x0, 0xc000502680, 0xc0004523c0, 0x6b?, 0x0, {0xc000f50940, 0x33})
	ui/item_status.go:104 +0xde
github.com/RasmusLindroth/tut/ui.drawNotification(0xc0000c6420, {0x300272822?, 0x0?}, 0xc0006463c0, 0x0?, 0xc0004523c0)
	ui/item_notification.go:35 +0x590
github.com/RasmusLindroth/tut/ui.DrawItem(0xc00061c270?, {0xa876f0, 0xc0000344c0}, 0xc000e6b950?, 0x21?, 0xa)
	ui/item.go:110 +0x4c6
github.com/RasmusLindroth/tut/ui.(*Feed).DrawContent(0xc0004523f0)
	ui/feed.go:85 +0xbc
github.com/RasmusLindroth/tut/ui.(*Timeline).DrawContent(...)
	ui/timeline.go:297
github.com/RasmusLindroth/tut/ui.(*Timeline).NextItemFeed(0xc00045c580)
	ui/timeline.go:398 +0xa7
github.com/RasmusLindroth/tut/ui.(*TutView).InputMainViewFeed(0x0?, 0x1?)
	ui/input.go:262 +0x40e
github.com/RasmusLindroth/tut/ui.(*TutView).InputMainView(0x1?, 0x0?)
	ui/input.go:226 +0x47
github.com/RasmusLindroth/tut/ui.(*TutView).Input(0xc0000c6420, 0xc000074d20?)
	ui/input.go:46 +0x24e
github.com/rivo/tview.(*Application).Run(0xc0003a00e0)
	/home/erici/go/pkg/mod/github.com/rivo/tview@v0.0.0-20230104153304-892d1a2eb0da/application.go:319 +0x66d
main.main()
	main.go:50 +0x3a9
```

**Comment by Saithe6** [comment]
I got this issue too, it seems to happen whenever I hit a specific notification.
![image](https://github.com/user-attachments/assets/2817a3bd-ab91-47e2-bcb5-ef49c9dca4f1)
this is the notification in the mobile app
