### ISSUE TITLE
Follow request notifications cause crash

### ISSUE THREAD

**Issue by justjosias** [RasmusLindroth/tut#47]
Whenever a follow request is reached in the notifications timeline, nothing is displayed. If subsequently the next or previous notification is selected, the program crashes due to a runtime memory error.

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x168 pc=0x7a777e]

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1(0xc00020a000)
	/home/josias/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210624155130-5f8430624688/application.go:243 +0x87
panic(0x8106a0, 0xb1b410)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
main.(*NotificationsFeed).Input(0xc0005aa080, 0xc00028c000)
	/home/josias/git/tut/feed.go:1175 +0x9e
main.(*StatusView).inputBoth(0xc000408060, 0xc00028c000)
	/home/josias/git/tut/statusview.go:192 +0x98
main.(*StatusView).Input(0xc000408060, 0xc00028c000, 0xc00020a000)
	/home/josias/git/tut/statusview.go:282 +0x39
main.main.func1(0xc00028c000, 0xc0003f58d8)
	/home/josias/git/tut/main.go:288 +0x62f
github.com/rivo/tview.(*Application).Run(0xc00020a000, 0x0, 0x0)
	/home/josias/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210624155130-5f8430624688/application.go:318 +0x785
main.main()
	/home/josias/git/tut/main.go:325 +0x1036
```

I propose that notifications that are not understood by be rendered somehow or with an error message instead of a crash. In addition, follow requests should be handled by tut, allowing accepting and rejecting them in the UI somehow.

**Comment by RasmusLindroth** [comment]
It should be fixed now. Thank you for noticing it. Accepting requests will be on the to do list :)
